const GET_USERS = 'GET_USERS';
const POST_USER = 'POST_USER';
const DELETE_USER = 'DELETE_USER';
const UPDATE_USER = 'UPDATE_USER';
const LOADING = 'LOADING';

export { GET_USERS, POST_USER, UPDATE_USER, DELETE_USER,LOADING };
